//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlam1.entityFramwork_gorom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recept
    {
        public int ReceptID { get; set; }
        public string Titel { get; set; }
        public string Beskrivning { get; set; }
        public string Ingredienser { get; set; }
        public int kategoriID { get; set; }
    
        public virtual Kategorier Kategorier { get; set; }
    }
}
